import { nanoid } from "@reduxjs/toolkit";
import green from "../.././assets/images/green.jpg";
import red from "../.././assets/images/red.jpg";

export const dataShopOnline = [
  {
    id: nanoid(),
    img: green,
    name: "Lụa in 3D r",
    price: 380,
    quantity: 380,
  },
  {
    id: nanoid(),
    img: green,
    name: "Lụa in 3D",
    price: 370,
    quantity: 370,
  },
  {
    id: nanoid(),
    img: green,
    name: "Lụa in 3D",
    price: 360,
    quantity: 360,
  },
  {
    id: nanoid(),
    img: green,
    name: "Lụa in 3D",
    price: 320,
    quantity: 320,
  },
  {
    id: nanoid(),
    img: green,
    name: "Lụa in 3D",
    price: 315,
    quantity: 315,
  },
  {
    id: nanoid(),
    img: green,
    name: "Lụa in 3D",
    price: 330,
    quantity: 330,
  },
  {
    id: nanoid(),
    img: green,
    name: "Lụa in 3D",
    price: 400,
    quantity: 400,
  },
  {
    id: nanoid(),
    img: green,
    name: "Lụa in 3D",
    price: 390,
    quantity: 390,
  },
  {
    id: nanoid(),
    img: green,
    name: "Lụa in 3D",
    price: 350,
    quantity: 350,
  },
  {
    id: nanoid(),
    img: green,
    name: "Lụa in 3D",
    price: 310,
    quantity: 310,
  },
  {
    id: nanoid(),
    img: red,
    name: "Lụa in 3D",
    price: 220,
    quantity: 220,
  },
  {
    id: nanoid(),
    img: red,
    name: "Lụa in 3D",
    price: 520,
    quantity: 520,
  },
  {
    id: nanoid(),
    img: red,
    name: "Lụa in 3D",
    price: 420,
    quantity: 420,
  },
  {
    id: nanoid(),
    img: red,
    name: "Lụa in 3D",
    price: 340,
    quantity: 340,
  },
  {
    id: nanoid(),
    img: red,
    name: "Lụa in 3D",
    price: 330,
    quantity: 330,
  },
  {
    id: nanoid(),
    img: red,
    name: "Lụa in 3D",
    price: 190,
    quantity: 190,
  },
  {
    id: nanoid(),
    img: red,
    name: "Lụa in 3D",
    price: 200,
    quantity: 200,
  },
  {
    id: nanoid(),
    img: red,
    name: "Lụa in 3D",
    price: 380,
    quantity: 380,
  },
  {
    id: nanoid(),
    img: red,
    name: "Lụa in 3D",
    price: 310,
    quantity: 310,
  },
  {
    id: nanoid(),
    img: red,
    name: "Lụa in 3D",
    price: 300,
    quantity: 300,
  },
];
